import pandas as pd 
df = pd.read_csv('exam_scores.csv') 
print("Student details\n") 
print(df) 
print("\nDetails of first three students\n") 
print(df[:3]) 
print("\nName and score of all the students\n") 
print(df[["Name","Score"]]) 
print("\nDetails of qualified students\n") 
print(df[df["Qualified"]=="yes" ]) 
print("\nDetails of students who made two or more attempts\n") 
print(df[df["Attempts"] > 1 ]) 
print("\n Mean score of students\n") 
print(round(df["Score"].mean(),2)) 
print("\n Student details in decreasing order of scores\n") 
print(df.sort_values("Score", ascending=False)) 
